name: Android Release CI

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch: 
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Auto-generate Keystore and Properties
      run: |
        rm -f key.jks
        keytool -genkey -v -keystore key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias myalias -dname "CN=ReVanced" -storepass 123456 -keypass 123456
        
        echo KEYSTORE_PASSWORD=123456 > signing.properties
        echo KEYSTORE_ALIAS=myalias >> signing.properties
        echo KEYSTORE_ALIAS_PASSWORD=123456 >> signing.properties
        echo KEYSTORE_FILE=../key.jks >> signing.properties

    - name: Build Release
      run: ./gradlew assembleUniversalRelease

    - run: |
        cd app/build/outputs/apk/universal/release/
        mv app-universal-release.apk ReVancedXposed-${{ github.ref_name }}.apk
        gh release create --prerelease ${{ github.ref_name }} ReVancedXposed-${{ github.ref_name }}.apk
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
